apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-test-server
  template:
    metadata:
      labels:
        app: load-test-server
    spec:
      containers:
      - name: load-test-server
        image: your-registry/load-test-server:latest
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 5201
          name: iperf
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
        env:
        - name: HTTP_PORT
          value: "8000"
        - name: IPERF_PORT
          value: "5201"
        - name: CPU_INTENSITY
          value: "100000"
        - name: MEMORY_SIZE
          value: "50"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: load-test-server
spec:
  selector:
    app: load-test-server
  ports:
  - name: http
    port: 80
    targetPort: 8000
  - name: iperf
    port: 5201
    targetPort: 5201
    protocol: TCP
  type: ClusterIP